# Maku settings.
name: まくノート
url: https://maku77.github.io

# Prevent the following files from converting by Jekyll.
exclude: [README.md,run.bat,run.sh]

# Enable highlighter.
highlighter: pygments

# Parse markdown files just like GitHub Flavored Markdown.
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Layout settings.
defaults:
  -
    scope:
      path: ""  # an empty string here means all files in the project
      type: "pages"  # exclude raw files such as files in the css directory
    values:
      layout: "default"  # use _layout/default.html
  -
    scope:
      path: "android"
      type: "pages"
    values:
      category_title: "Android ノート"
      category_name: "android"
  -
    scope:
      path: "bestpractice"
      type: "pages"
    values:
      category_title: "Bestpractice ノート"
      category_name: "bestpractice"
  -
    scope:
      path: "docker"
      type: "pages"
    values:
      category_title: "Docker ノート"
      category_name: "docker"
  -
    scope:
      path: "git"
      type: "pages"
    values:
      category_title: "Git ノート"
      category_name: "git"
  -
    scope:
      path: "gradle"
      type: "pages"
    values:
      category_title: "Gradle ノート"
      category_name: "gradle"
  -
    scope:
      path: "java"
      type: "pages"
    values:
      category_title: "Java ノート"
      category_name: "java"
  -
    scope:
      path: "mt"
      type: "pages"
    values:
      category_title: "Meta Trader ノート"
      category_name: "mt"
  -
    scope:
      path: "p4"
      type: "pages"
    values:
      category_title: "Perforce ノート"
      category_name: "p4"
  -
    scope:
      path: "program"
      type: "pages"
    values:
      category_title: "Program ノート"
      category_name: "program"
  -
    scope:
      path: "python"
      type: "pages"
    values:
      category_title: "Python ノート"
      category_name: "python"
  -
    scope:
      path: "ruby"
      type: "pages"
    values:
      category_title: "Ruby ノート"
      category_name: "ruby"
  -
    scope:
      path: "sed"
      type: "pages"
    values:
      category_title: "sed ノート"
      category_name: "sed"
  -
    scope:
      path: "shell"
      type: "pages"
    values:
      category_title: "Shell ノート"
      category_name: "shell"
  -
    scope:
      path: "web"
      type: "pages"
    values:
      category_title: "HTML/CSS ノート"
      category_name: "web"
  -
    scope:
      path: "windows"
      type: "pages"
    values:
      category_title: "Windows ノート"
      category_name: "windows"

