# Maku settings.
name: まくノート
url: https://maku77.github.io

# Prevent the following files from converting by Jekyll.
exclude: [README.md,run.bat,run.sh]

# Enable highlighter.
# highlighter: pygments
highlighter: rouge

# Parse markdown files just like GitHub Flavored Markdown.
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false  # Not insert BR for each line

# Layout settings.
defaults:
  -
    scope:
      path: ""  # an empty string here means all files in the project
      type: "pages"  # exclude raw files such as files in the css directory
    values:
      layout: "default"  # use _layout/default.html
      category_id: "NONE"
      category_desc: "天才星人まくのソフトウェア開発に関するノート"
      category_logo: "logo.jpg"

  # このカテゴリだけトップに表示するため、最初に定義しておく
  -
    scope:
      path: "memo"
      type: "pages"
    values:
      category_title: "いろいろ"
      category_id: "memo"
      category_logo: "logo-program.svg"
      category_desc: "天才星人まくのごちゃまぜノート"
      category_long_desc: "ソフトウェア開発のベストプラクティス、現場での気付き、ブックレビューなど。"

  -
    scope:
      path: "android"
      type: "pages"
    values:
      category_title: "Android"
      category_id: "android"
      category_logo: "logo-android.png"
      category_desc: "天才星人まくの Android ノート"
      category_long_desc: "Android スマホアプリ、Android TV の開発に関して。"
  -
    scope:
      path: "cpp"
      type: "pages"
    values:
      category_title: "C/C++"
      category_id: "cpp"
      category_logo: "logo-cpp.svg"
      category_desc: "天才星人まくの C/C++ ノート"
      category_long_desc: "ポインタポインタポインター！"
  -
    scope:
      path: "docker"
      type: "pages"
    values:
      category_title: "Docker"
      category_id: "docker"
      category_logo: "logo-docker.png"
      category_desc: "天才星人まくの Docker ノート"
      category_long_desc: "アプリケーション実行環境をコンテナ化し、柔軟なデプロイを可能にする Docker の使い方。"
  -
    scope:
      path: "git"
      type: "pages"
    values:
      category_title: "Git"
      category_id: "git"
      category_logo: "logo-github.png"
      category_desc: "天才星人まくの Git/GitHub ノート"
      category_long_desc: "Git によるバージョン管理と、GitHub 特有の話もあるよ。"
  -
    scope:
      path: "gradle"
      type: "pages"
    values:
      category_title: "Gradle"
      category_id: "gradle"
      category_logo: "logo-gradle.png"
      category_desc: "天才星人まくの Gradle ノート"
      category_long_desc: "Java の最新のビルドシステム Gradle の使い方。"
  -
    scope:
      path: "web"
      type: "pages"
    values:
      category_title: "HTML/CSS"
      category_id: "web"
      category_logo: "logo-html5.svg"
      category_desc: "天才星人まくの HTML/CSS ノート"
      category_long_desc: "スタイルシートの使い方や、Web 用パーツサンプルなど。"
  -
    scope:
      path: "java"
      type: "pages"
    values:
      category_title: "Java"
      category_id: "java"
      category_logo: "logo-java.svg"
      category_desc: "天才星人まくの Java ノート"
      category_long_desc: "Android のおかげで息を吹き返した感のある Java。"
  -
    scope:
      path: "js"
      type: "pages"
    values:
      category_title: "JavaScript"
      category_id: "js"
      category_logo: "logo-js.svg"
      category_desc: "天才星人まくの JavaScript ノート"
      category_long_desc: "Web プログラマにとって必須の言語。"
  -
    scope:
      path: "linux"
      type: "pages"
    values:
      category_title: "Linux/Shell"
      category_id: "linux"
      category_logo: "logo-linux.svg"
      category_desc: "天才星人まくの Linux/Shell ノート"
      category_long_desc: "Linux 全般のメモ。Bash や Linux シェルプログラミングなど。"
  -
    scope:
      path: "middleman"
      type: "pages"
    values:
      category_title: "Middleman"
      category_id: "middleman"
      category_logo: "logo-middleman.svg"
      category_desc: "天才星人まくの Middleman ノート"
      category_long_desc: "静的サイトジェネレータ Middleman の使い方。"
  -
    scope:
      path: "mt"
      type: "pages"
    values:
      category_title: "Meta Trader"
      category_id: "mt"
      category_logo: "logo-metatrader.png"
      category_desc: "天才星人まくの Meta Trader ノート"
      category_long_desc: "メタトレーダーを使った FX 自動売買（シストレ）プログラミングについて。"
  -
    scope:
      path: "nodejs"
      type: "pages"
    values:
      category_title: "Node.js"
      category_id: "nodejs"
      category_logo: "logo-nodejs.svg"
      category_desc: "天才星人まくの Node JS ノート"
      category_long_desc: "今やクライアントもサーバも Node.js でバッチシ。"
  -
    scope:
      path: "p4"
      type: "pages"
    values:
      category_title: "Perforce"
      category_id: "p4"
      category_logo: "logo-p4.jpg"
      category_desc: "天才星人まくの Perforce ノート"
      category_long_desc: "p4 コマンドや p4v についていろいろ。"
  -
    scope:
      path: "perl"
      type: "pages"
    values:
      category_title: "Perl"
      category_id: "perl"
      category_logo: "logo-perl.svg"
      category_desc: "天才星人まくの Perl ノート"
      category_long_desc: "おそらくもうオワコンな言語、Perl。"
  -
    scope:
      path: "php"
      type: "pages"
    values:
      category_title: "PHP"
      category_id: "php"
      category_logo: "logo-php.svg"
      category_desc: "天才星人まくの PHP ノート"
      category_long_desc: "サーバサイド言語の世界で一世を風靡した PHP。CodeIgnitor は RoR よりも手軽でオススメ。"
  -
    scope:
      path: "python"
      type: "pages"
    values:
      category_title: "Python"
      category_id: "python"
      category_logo: "logo-python.png"
      category_desc: "天才星人まくの Python ノート"
      category_long_desc: "海外で主流のオブジェクト指向言語 Python の使い方。"
  -
    scope:
      path: "r"
      type: "pages"
    values:
      category_title: "R"
      category_id: "r"
      category_logo: "logo-r.svg"
      category_desc: "天才星人まくの R ノート"
      category_long_desc: "統計解析やグラフプロットに便利な R の入門。"
  -
    scope:
      path: "ruby"
      type: "pages"
    values:
      category_title: "Ruby"
      category_id: "ruby"
      category_logo: "logo-ruby.jpg"
      category_desc: "天才星人まくの Ruby ノート"
      category_long_desc: "日本で生まれたオブジェクト指向言語 Ruby の使い方。"
  -
    scope:
      path: "sed"
      type: "pages"
    values:
      category_title: "sed/awk"
      category_id: "sed"
      category_logo: "logo-text.png"
      category_desc: "天才星人まくの Sed/Awk ノート"
      category_long_desc: "Linux 系のコマンドを用いたテキスト処理いろいろ。"
  -
    scope:
      path: "vagrant"
      type: "pages"
    values:
      category_title: "Vagrant"
      category_id: "vagrant"
      category_logo: "logo-vagrant.svg"
      category_desc: "天才星人まくの Vagrant ノート"
      category_long_desc: "仮想環境の立ち上げ＆設定の自動化に関するメモ。"
  -
    scope:
      path: "vim"
      type: "pages"
    values:
      category_title: "Vim"
      category_id: "vim"
      category_logo: "logo-vim.svg"
      category_desc: "天才星人まくの Vim ノート"
      category_long_desc: "素敵なテキストエディタ Vim のメモ。"
  -
    scope:
      path: "windows"
      type: "pages"
    values:
      category_title: "Windows"
      category_id: "windows"
      category_logo: "logo-windows.jpg"
      category_desc: "天才星人まくの Windows ノート"
      category_long_desc: "Windows の便利な使い方や、バッチファイルによるプログラミング方法。"

