# Maku settings.
name: まくノート
url: https://maku77.github.io

# Prevent the following files from converting by Jekyll.
exclude: [README.md,run.bat,run.sh]

# Enable highlighter.
highlighter: pygments

# Parse markdown files just like GitHub Flavored Markdown.
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Layout settings.
defaults:
  -
    scope:
      path: ""  # an empty string here means all files in the project
      type: "pages"  # exclude raw files such as files in the css directory
    values:
      layout: "default"  # use _layout/default.html
  -
    scope:
      path: "android"
      type: "pages"
    values:
      layout: "android"
  -
    scope:
      path: "bestpractice"
      type: "pages"
    values:
      layout: "bestpractice"
  -
    scope:
      path: "docker"
      type: "pages"
    values:
      layout: "docker"
  -
    scope:
      path: "git"
      type: "pages"
    values:
      layout: "git"
  -
    scope:
      path: "gradle"
      type: "pages"
    values:
      layout: "gradle"
  -
    scope:
      path: "java"
      type: "pages"
    values:
      layout: "java"
  -
    scope:
      path: "mt"
      type: "pages"
    values:
      layout: "mt"
  -
    scope:
      path: "p4"
      type: "pages"
    values:
      layout: "p4"
  -
    scope:
      path: "program"
      type: "pages"
    values:
      layout: "program"
  -
    scope:
      path: "python"
      type: "pages"
    values:
      layout: "python"
  -
    scope:
      path: "ruby"
      type: "pages"
    values:
      layout: "ruby"
  -
    scope:
      path: "sed"
      type: "pages"
    values:
      layout: "sed"
  -
    scope:
      path: "shell"
      type: "pages"
    values:
      layout: "shell"
  -
    scope:
      path: "web"
      type: "pages"
    values:
      layout: "web"

